### PR TITLE
Model fix

### PR DESCRIPTION
**Pull request by twistfire92**
add default value for extra_fields

### CODE REVIEW

**Comment by hall-b** [comment]
Bad idea to initialize directly with a dictionary.  
Cf: https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422
Better do: `extra_fields: Optional[dict] = Field(default_factory=lambda: dict())`

**Comment by yannicschroeer** [comment]
Agreed, default value for dictionaries should either be a factory method or `None` (Which it was before). Anyway, why is a default value necessary?

**Comment by twistfire92** [comment]
> Bad idea to initialize directly with a dictionary.
> Cf: https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422
> Better do: `extra_fields: Optional[dict] = Field(default_factory=lambda: dict())`

Or just `Field(default_factory=dict)`

**Comment by yannicschroeer** [comment]
> > Bad idea to initialize directly with a dictionary.
> > Cf: https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422
> > Better do: `extra_fields: Optional[dict] = Field(default_factory=lambda: dict())`
> 
> Or just `Field(default_factory=dict)`

I'd prefer this. No need for a lambda

**Comment by twistfire92** [comment]
> > > Bad idea to initialize directly with a dictionary.
> > > Cf: https://towardsdatascience.com/python-pitfall-mutable-default-arguments-9385e8265422
> > > Better do: `extra_fields: Optional[dict] = Field(default_factory=lambda: dict())`
> > 
> > 
> > Or just `Field(default_factory=dict)`
> 
> I'd prefer this. No need for a lambda

fixed!

**Review by yannicschroeer — APPROVED** [review]

**Review by JonasScholl — APPROVED** [review]

**Pull request merged**
